0.3.0: Remove rand from public API, remove from_crypto_rng, update dependencies to the latest.
fadeevab/cocoon pull request #12
Opened 2021-09-18 21:23 UTC by fadeevab

Remove `rand` types from `Cocoon` public API
---------------------------------------------------

Problem: `cocoon` exposes `RngCore`, `CryptoRng`, `StdRng`, and `ThreadRng` in its public API. Using the incompatible versions of the crate breaks the build.

`Cocoon::from_crypto_rng` must be removed from public API, because it cannot be implemented without generic type and dependency on `rand` in `Cocoon` struct.

`enum RngVariant` is a wrapper around of `StdRng` and `ThreadRng` for "nostd" builds (no `alloc` crate, no `Box`).

Bumping versions of dependencies
---------------------------------------

Test vectors of encryption methods are updated. StdRng was changed from ChaCha20 to ChaCha12 in the new version of `rand`, which leads to a change in seed generation. It's okay since decryption works in a backward-compatible manner as expected. Also, it is actually expected to have a random seed in a wild, so tests just unveiled the issue which is good.

2021-09-18 21:31 UTC, fadeevab commented
@bhgomes Please, review. :)

2021-09-18 22:06 UTC, bhgomes commented
Thanks for the PR! I'll take a look at it tonight.

2021-09-19 03:37 UTC, bhgomes requested changes
LGTM. I would just run `clippy` again and fix those redundant references and the comments I made above.

2021-09-19 09:22 UTC, fadeevab commented on src/lib.rs
> +#[allow(clippy::clippy::large_enum_variant)]
Right, for some reason both notions work 🤷‍♂️ I double-checked

2021-09-19 09:24 UTC, fadeevab commented on src/lib.rs
> +#[allow(clippy::clippy::large_enum_variant)]
Also, clippy doesn't show me those redundant references warning

2021-09-19 15:54 UTC, bhgomes commented
Oh, sorry, I'm seeing the extra `clippy` warnings cause I'm using nightly `clippy`. Up to you if you want to follow that.

2021-09-19 16:30 UTC, merged

2021-09-19 16:35 UTC, fadeevab commented
@bhgomes Hey! Maybe, before I publish 0.3.0, you could try the `master` branch locally?.. Thank you for your help!

2021-09-19 18:01 UTC, bhgomes commented
@fadeevab It looks good to me. Thanks for the upgrade!

2021-09-19 20:56 UTC, fadeevab commented
@bhgomes Published. Thank you!